/*API IP ADDRESS*/
export const BASE_URL = 'http://41.175.8.230:8084';

/* BATCH INSPECTION CONSTANTS*/
export const CREATE_IQM_BATCH_INSPECTION = "CREATE_IQM_BATCH_INSPECTION";
export const GET_IQM_BATCH_INSPECTION = "GET_IQM_BATCH_INSPECTION";
export const DELETE_IQM_BATCH_INSPECTION = "DELETE_IQM_BATCH_INSPECTION";
export const LIST_IQM_BATCH_INSPECTIONS ="LIST_IQM_BATCH_INSPECTIONS"; 

/* STANDARD CONSTANTS*/
export const CREATE_STANDARD = "CREATE_STANDARD";
export const GET_STANDARD = "GET_STANDARD";
export const DEACTIVE_STANDARD = "DEACTIVE_STANDARD";
export const LIST_STANDARDS ="LIST_STANDARDS";

/* COUNTRY CONSTANTS */
export const LIST_COUNTRIES = "LIST_COUNTRIES";

/* PRODUCTS CONSTANTS*/
export const LIST_PRODUCTS = "LIST_PRODUCTS";
export const GET_PRODUCT = "GET_PRODUCT";

/* PRODUCTS CONSTANTS*/
export const LIST_TOWNS = "LIST_TOWNS";

/* PRODUCTS CONSTANTS*/
export const LIST_STATIONS = "LIST_STATIONS";

/*PRODUCT CHECKLIST*/
export const GET_PRODUCT_CHECK_LISTS = "GET_PRODUCT_CHECK_LISTS";
export const GET_PRODUCT_CHECK_LIST = "GET_PRODUCT_CHECK_LIST";
export const CREATE_PRODUCT_CHECK_LIST = "CREATE_PRODUCT_CHECK_LIST";
export const DELETE_PRODUCT_CHECK_LIST = "DELETE_PRODUCT_CHECK_LIST";

/* SAMPLE REQUEST FORM */
export const CREATE_SAMPLE_REQUEST_FORM = "CREATE_SAMPLE_REQUEST_FORM";
export const GET_SAMPLE_REQUEST_FORMS = "GET_SAMPLE_REQUEST_FORMS";
export const GET_SAMPLE_REQUEST_FORM = "GET_SAMPLE_REQUEST_FORM";
export const CREATE_SAMPLE_SUBMISSION_FORM = "CREATE_SAMPLE_SUBMISSION_FORM";



/* ASCUYDA*/
export const LIST_ASCUYDA_APPLICATIONS = "LIST_ASCUYDA_APPLICATIONS";

/** INSPECTORS CONSTANTS */
export const LIST_INSPECTORS = "LIST_INSPECTORS";

/* INSPECTION FORM */
export const GET_INSPECTION_REPORT ="GET_INSPECTION_REPORT";
export const LIST_IQM_INSPECTION_REPORT = "LIST_IQM_INSPECTION_REPORT";
export const CREATE_INSPECTION_REPORT="CREATE_INSPECTION_REPORT";


export const LIST_IQM_SAMPLE_SUBMISSION = "LIST_IQM_SAMPLE_SUBMISSION";